apiVersion: v1
kind: Service
metadata:
  name: qwen3-tts-spanish-service
  namespace: letta-agent
spec:
  type: NodePort
  selector:
    app: qwen3-tts-spanish-service
  ports:
    - port: 8880
      targetPort: 8880
      nodePort: 30881
